import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Mail, MessageSquare, CheckCircle, Package, Clock, AlertTriangle, ExternalLink, CheckCircle2 } from 'lucide-react';
import { getNotifications, markAsRead, markAllAsRead } from '../utils/notifications.js';
import { formatDate } from '../utils/date.js';

export function NotificationsPage() {
  const [notifications, setNotifications] = useState([]);
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    /*
     * The notification page reads existing notifications from localStorage when
     * it opens. This makes notifications persistent during browser refreshes.
     */
    setNotifications(getNotifications());
    
    /*
     * Other pages can create notifications after booking a delivery or updating
     * status. They dispatch `scdm_notification_event`, and this listener updates
     * the inbox immediately without refreshing the page.
     */
    const handleUpdate = () => setNotifications(getNotifications());
    window.addEventListener('scdm_notification_event', handleUpdate);
    return () => window.removeEventListener('scdm_notification_event', handleUpdate);
  }, []);

  const handleSelect = (notif) => {
    setSelected(notif);
    if (!notif.read) {
      /*
       * Opening an unread notification marks it as read.
       * This also updates the topbar unread count through the custom event.
       */
      markAsRead(notif.id);
    }
  };

  const getIcon = (type) => {
    /*
     * Notification type controls the visual style.
     * Email notifications use a mail icon, while SMS notifications use a
     * message icon, helping the user understand the source quickly.
     */
    if (type === 'email') return <Mail size={18} className="text-blue-400" />;
    return <MessageSquare size={18} className="text-green-400" />;
  };

  const renderEmailContent = (notif) => (
    /*
     * Email notifications are rendered like an official courier receipt.
     * This is useful in the demo because booking confirmation looks similar to
     * what a real customer email could contain.
     */
    <div style={{ background: '#ffffff', color: '#1e293b', padding: '2rem', borderRadius: '8px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}>
      <div style={{ borderBottom: '2px solid #f1f5f9', paddingBottom: '1.5rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>
        <Package size={32} color="#3b82f6" />
        <div>
          <h2 style={{ fontSize: '1.5rem', fontWeight: 800, margin: 0, color: '#0f172a' }}>SmartCourier</h2>
          <p style={{ color: '#64748b', fontSize: '0.875rem', margin: 0 }}>Official Delivery Receipt</p>
        </div>
      </div>
      
      <h3 style={{ fontSize: '1.25rem', fontWeight: 600, marginBottom: '1rem', color: '#1e293b' }}>{notif.title}</h3>
      
      <p style={{ fontSize: '1rem', lineHeight: 1.6, color: '#334155', marginBottom: '1.5rem' }}>
        {notif.message}
      </p>

      {notif.trackingNumber && (
        <div style={{ background: '#f8fafc', padding: '1.5rem', borderRadius: '8px', border: '1px dashed #cbd5e1', marginBottom: '1.5rem' }}>
          <p style={{ fontSize: '0.875rem', color: '#64748b', margin: '0 0 0.5rem 0', textTransform: 'uppercase', fontWeight: 700 }}>Tracking Number</p>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <p style={{ fontSize: '1.5rem', fontFamily: 'monospace', fontWeight: 700, color: '#3b82f6', margin: 0, letterSpacing: '2px' }}>{notif.trackingNumber}</p>
          </div>
        </div>
      )}

      <p style={{ fontSize: '0.9rem', color: '#64748b', margin: 0 }}>
        Thank you for choosing SmartCourier.<br/>
        This is an automated message generated by the SmartCourier Notification Gateway.
      </p>
    </div>
  );

  const renderSmsContent = (notif) => (
    /*
     * SMS notifications are rendered as compact message bubbles.
     * This visually separates quick delivery alerts from detailed email-style
     * booking receipts.
     */
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', maxWidth: '400px', margin: '0 auto' }}>
      <p style={{ textAlign: 'center', fontSize: '0.75rem', color: '#64748b', textTransform: 'uppercase', letterSpacing: '1px' }}>
        {formatDate(notif.date)}
      </p>
      
      <div style={{ alignSelf: 'flex-start', background: '#1e293b', padding: '1rem', borderRadius: '1rem 1rem 1rem 0', maxWidth: '85%', border: '1px solid rgba(255,255,255,0.05)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
          <MessageSquare size={14} color="#10b981" />
          <span style={{ fontSize: '0.75rem', fontWeight: 600, color: '#94a3b8' }}>SmartCourier SMS Alert</span>
        </div>
        <p style={{ margin: 0, fontSize: '0.95rem', lineHeight: 1.4, color: '#f1f5f9' }}>
          {notif.message}
        </p>
        {notif.trackingNumber && (
          <p style={{ margin: '0.5rem 0 0 0', fontSize: '0.85rem', color: '#60a5fa', fontFamily: 'monospace' }}>
            TRK: {notif.trackingNumber}
          </p>
        )}
      </div>
    </div>
  );

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="fade-in" style={{ height: 'calc(100vh - 120px)', display: 'flex', flexDirection: 'column' }}>
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: '1.5rem' }}>
        <div>
          <h1>Notification Gateway</h1>
          <p>Simulated Email and SMS Inbox for system alerts.</p>
        </div>
        <button 
          onClick={markAllAsRead}
          className="btn-outline" 
          style={{ width: 'auto', border: '1px solid rgba(16, 185, 129, 0.3)', color: '#10b981', background: 'rgba(16, 185, 129, 0.1)' }}
        >
          <CheckCircle2 size={16} /> Mark all read
        </button>
      </div>

      <div style={{ display: 'flex', flex: 1, gap: '1.5rem', minHeight: 0 }}>
        {/* Inbox List */}
        <div className="glass-card" style={{ flex: '1 1 350px', maxWidth: '400px', display: 'flex', flexDirection: 'column', padding: '0', overflow: 'hidden' }}>
          <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid rgba(255,255,255,0.05)', background: 'rgba(0,0,0,0.2)' }}>
            <h2 style={{ fontSize: '1.1rem', fontWeight: 600, margin: 0 }}>Inbox</h2>
          </div>
          
          <div style={{ overflowY: 'auto', flex: 1 }}>
            {notifications.length > 0 ? notifications.map((notif) => (
              <div 
                key={notif.id}
                onClick={() => handleSelect(notif)}
                style={{ 
                  padding: '1.25rem 1.5rem', 
                  borderBottom: '1px solid rgba(255,255,255,0.05)', 
                  cursor: 'pointer',
                  background: selected?.id === notif.id ? 'rgba(59, 130, 246, 0.1)' : notif.read ? 'transparent' : 'rgba(255,255,255,0.02)',
                  borderLeft: notif.read ? '3px solid transparent' : '3px solid #3b82f6',
                  transition: 'all 0.2s ease'
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.5rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    {getIcon(notif.type)}
                    <span style={{ fontSize: '0.8rem', textTransform: 'uppercase', fontWeight: 700, color: notif.type === 'email' ? '#60a5fa' : '#34d399' }}>
                      {notif.type}
                    </span>
                  </div>
                  <span style={{ fontSize: '0.75rem', color: '#64748b' }}>
                    {formatDate(notif.date).split(',')[0]}
                  </span>
                </div>
                <h3 style={{ fontSize: '0.95rem', fontWeight: notif.read ? 500 : 700, color: notif.read ? '#e2e8f0' : '#ffffff', margin: '0 0 0.25rem 0', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                  {notif.title}
                </h3>
                <p style={{ fontSize: '0.85rem', color: '#94a3b8', margin: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                  {notif.message}
                </p>
              </div>
            )) : (
              <div style={{ padding: '3rem 1.5rem', textAlign: 'center', color: '#64748b' }}>
                <Mail size={32} style={{ margin: '0 auto 1rem auto', opacity: 0.5 }} />
                <p>Your inbox is empty.</p>
              </div>
            )}
          </div>
        </div>

        {/* Message Viewer */}
        <div className="glass-card" style={{ flex: '2 1 600px', display: 'flex', flexDirection: 'column', background: 'rgba(15, 23, 42, 0.8)', overflowY: 'auto' }}>
          {selected ? (
            <AnimatePresence mode="wait">
              <motion.div 
                key={selected.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.98 }}
                style={{ width: '100%', maxWidth: selected.type === 'email' ? '600px' : '100%', margin: '0 auto' }}
              >
                {selected.type === 'email' ? renderEmailContent(selected) : renderSmsContent(selected)}
              </motion.div>
            </AnimatePresence>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: '#64748b' }}>
              <Package size={48} style={{ marginBottom: '1.5rem', opacity: 0.3 }} />
              <p style={{ fontSize: '1.1rem' }}>Select a notification to view its contents</p>
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}
